# Generated by Django 3.2.4 on 2021-07-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0002_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Author',
        ),
    ]
