# Generated by Django 3.0.7 on 2020-07-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0002_auto_20200704_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Author',
        ),
    ]
