# Generated by Django 3.0.7 on 2020-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_auto_20200704_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='store_image/1', null=True, upload_to='store_image/'),
        ),
    ]
