# Generated by Django 3.0.7 on 2020-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0005_auto_20200715_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='store_image/1.jpg', null=True, upload_to='store_image/'),
        ),
    ]
