# Generated by Django 3.0.7 on 2020-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0006_auto_20200715_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store_image/'),
        ),
    ]
