# Generated by Django 3.2.4 on 2021-10-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_rename_name_book_author'),
        ('tp_book', '0007_auto_20200715_1029'),
    ]

    operations = [
    ]
